### ISSUE TITLE
Hello please help me to solve below shown problem 

### ISSUE THREAD

**Issue by ankurmani** [orbitdb/go-orbit-db#1]
i am getting the error shown below...please help me to solve it.

ankur@ankur:~/Documents/project_blockchain/GOPATH/src/github.com/orbitdb/go-orbit-db/cmd/orbitdb$ ./orbitdb create ank feed
panic: Post https://localhost:3000/db/ank: dial tcp 127.0.0.1:3000: connect: connection refused

goroutine 1 [running]:
github.com/orbitdb/go-orbit-db/http.(*Request).Post(0xc000105ce0, 0xc000024b00, 0x1f)
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/orbitdb/go-orbit-db/http/request.go:93 +0x4de
github.com/orbitdb/go-orbit-db/cmd/orbitdb/cmd.glob..func2(0xcea820, 0xc00000e7e0, 0x2, 0x2)
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/orbitdb/go-orbit-db/cmd/orbitdb/cmd/create.go:32 +0x230
github.com/spf13/cobra.(*Command).execute(0xcea820, 0xc00000e760, 0x2, 0x2, 0xcea820, 0xc00000e760)
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/spf13/cobra/command.go:835 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xcec3a0, 0x43cf1a, 0xcb1460, 0xc000000180)
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/spf13/cobra/command.go:919 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/spf13/cobra/command.go:869
github.com/orbitdb/go-orbit-db/cmd/orbitdb/cmd.Execute()
	/home/ankur/Documents/project_blockchain/GOPATH/src/github.com/orbitdb/go-orbit-db/cmd/orbitdb/cmd/root.go:26 +0x31
main.main()

**Comment by damien-white** [comment]
Can you please start by providing some additional information about the system that you are running this on (looks like some kind of linux-based distribution but I cannot tell which one based purely on this error dump.

To help you solve your problem for good, I need to try to find a way to reproduce the bug / error that you are experiencing first so that I can then go about fixing it.

Try and be as specific as possible; what platform are you running? Is there anything else about the environment you are running in that you think I should be aware of? Things like this would be a fantastic start. I am confident that I can help you fix your problem; I just need more information. The more details, the better!

In the meantime, I will try to reproduce your issue and if I can find a fix before you get back to me, I will open a PR to get it fixed ASAP.

Thank you!
